version: '3'
services:
  database-backup-manager:
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    container_name: database-backup-manager
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: src/app.py
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      network:
        ipv4_address: 172.28.0.2

  mysql:
    image: mysql:latest
    container_name: my_test_mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      network:
        ipv4_address: 172.28.0.3

  postgres:
    image: postgres:latest
    container_name: my_test_postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    networks:
      network:
        ipv4_address: 172.28.0.4

  mongo:
    image: mongo:latest
    container_name: my_test_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    networks:
      network:
        ipv4_address: 172.28.0.5

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16


# docker-compose up --build -d
# command: django-admin startproject app