services:
  app:
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    container_name: database-backup-manager
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: src/app.py
    ports:
      - 5000:5000
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: my_test_mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"


# docker-compose up --build -d
# command: django-admin startproject app