services:
  app:
    build: .
    container_name: database-backup-manager
    command: python src/app.py
    ports:
      - 5000:5000
    volumes:
      - .:/app


# docker-compose up --build -d
# command: django-admin startproject app