services:
  app:
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    container_name: database-backup-manager
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: src/app.py
    ports:
      - 5000:5000
    volumes:
      - .:/app


# docker-compose up --build -d
# command: django-admin startproject app