/**
 * Types for the system notification framework.
 *
 * System notifications are sent for configurable events (e.g. user login,
 * backup completion) through user-selected notification channels
 * (Email, Discord, etc.).
 */

/** All supported system notification event types */
export const NOTIFICATION_EVENTS = {
  USER_LOGIN: "user_login",
  USER_CREATED: "user_created",
  BACKUP_SUCCESS: "backup_success",
  BACKUP_FAILURE: "backup_failure",
  RESTORE_COMPLETE: "restore_complete",
  RESTORE_FAILURE: "restore_failure",
  CONFIG_BACKUP: "config_backup",
  SYSTEM_ERROR: "system_error",
} as const;

export type NotificationEventType =
  (typeof NOTIFICATION_EVENTS)[keyof typeof NOTIFICATION_EVENTS];

/** Metadata describing a notification event */
export interface NotificationEventDefinition {
  id: NotificationEventType;
  name: string;
  description: string;
  category: "auth" | "backup" | "restore" | "system";
  /** Default enabled state when first configured */
  defaultEnabled: boolean;
}

/** Payload generated by a template for adapter consumption */
export interface NotificationPayload {
  /** Short title (email subject, embed title, etc.) */
  title: string;
  /** Plain text message body */
  message: string;
  /** Structured fields for rich display (embeds, tables) */
  fields?: Array<{ name: string; value: string; inline?: boolean }>;
  /** Hex color for embeds / status indicators */
  color?: string;
  /** Whether the event represents a success or failure */
  success: boolean;
}

/** Data passed to template functions per event type */
export interface UserLoginData {
  userName: string;
  email: string;
  ipAddress?: string;
  userAgent?: string;
  timestamp: string;
}

export interface UserCreatedData {
  userName: string;
  email: string;
  createdBy?: string;
  timestamp: string;
}

export interface BackupResultData {
  jobName: string;
  sourceName?: string;
  duration?: number;
  size?: number;
  error?: string;
  executionId?: string;
  timestamp: string;
}

export interface RestoreResultData {
  sourceName?: string;
  targetDatabase?: string;
  duration?: number;
  error?: string;
  executionId?: string;
  timestamp: string;
}

export interface ConfigBackupData {
  fileName?: string;
  size?: number;
  encrypted: boolean;
  timestamp: string;
}

export interface SystemErrorData {
  component: string;
  error: string;
  details?: string;
  timestamp: string;
}

/** Union of all event data types for type-safe template dispatch */
export type NotificationEventData =
  | { eventType: typeof NOTIFICATION_EVENTS.USER_LOGIN; data: UserLoginData }
  | { eventType: typeof NOTIFICATION_EVENTS.USER_CREATED; data: UserCreatedData }
  | { eventType: typeof NOTIFICATION_EVENTS.BACKUP_SUCCESS; data: BackupResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.BACKUP_FAILURE; data: BackupResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.RESTORE_COMPLETE; data: RestoreResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.RESTORE_FAILURE; data: RestoreResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.CONFIG_BACKUP; data: ConfigBackupData }
  | { eventType: typeof NOTIFICATION_EVENTS.SYSTEM_ERROR; data: SystemErrorData };

/** Persisted notification configuration (stored as JSON in SystemSetting) */
export interface SystemNotificationConfig {
  /** Default channel IDs (AdapterConfig IDs) used when event has no override */
  globalChannels: string[];
  /** Per-event settings */
  events: Record<
    string,
    {
      enabled: boolean;
      /** Override channels for this event. null = use globalChannels */
      channels: string[] | null;
    }
  >;
}
